profiles: [github, bitbucket, codepen, gitlab, kaggle, stackoverflow]
skills:
  Frontend Frameworks: [html5, nodejs, ts, astro, react, redux, jquery]
  UI Frameworks: [css3, sass, twbs, twcss, zfd]
  Backend Frameworks: [aspnet, rails, codeigniter, sql]
  Artificial Intelligence: [tf, keras, _pytorch, numpy, pandas, opencv, sklearn]
  Programming Languages: [csharp, js, ruby, golang, python, php, cpp]
  Business Intelligence: [powerbi, msfabric, mssql, spark]
  Cloud Infrastructure: [azure, docker, k8s, _vercel, ado]
  Development Tools: [vs, vscode, ps, postman, git, figma, jupyter]
  _Databases: [mssql, mongodb, redis, pgsql, mysql]
  _Content Management Systems: [wp, drupal, joomla]
